In [1]:
a = [10, -33, 5, -23, -28, -138, 9, 10, -12, -2, 10, -43, 10, 10, 10, -165, 10, 10, -17, 6, -6, 9, -82, 9, 10, 10, -35, -66, -11, -72, -2, 8, -12, -126, 10, 10, 10, -61, -34, -46, 10, 10, 10, -1, -40, 8, 10, 10, 10, -44, 10, 10, 10, -113, 10, 10, 0, -84, 10, 10, 10, 10, -21, -67, 8, -42, -124, 10, -114, -62, 10, 9, -130, 10, 10, 10, 10, 10, 9, -67, -123, 10, -8, 10, 9, 10, -31, 0, -8, -62, -45, 10, -24, 10, -9, 10, -58, -77, -61, 10]

In [3]:
import numpy as np

In [3]:
a = np.array(a)

In [5]:
np.average(a)

-19.2

In [15]:
a=np.array([[1,1,1,1],[2,2,2,999]])

In [16]:
a

array([[  1,   1,   1,   1],
       [  2,   2,   2, 999]])

In [21]:
np.argwhere(a==999)[0]

array([1, 3], dtype=int64)

In [22]:
np.random.shuffle(a)

In [23]:
a

array([[  2,   2,   2, 999],
       [  1,   1,   1,   1]])